

const PROJECTS: Project[] = [
  // 🔥 PROJETS 1-6 (existants améliorés)
  {
    id: 1,
    title: "Portfolio Personnel v2",
    description: "Site web ultra-moderne avec animations 3D, PWA, mode sombre/clair adaptatif, SEO optimisé et performances Lighthouse 100%.",
    year: 2026,
    type: "Web",
    technologies: ["React", "Next.js 15", "Tailwind CSS", "Framer Motion"],
    link: "https://example.com",
    github: "https://github.com/username/portfolio-v2",
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    mode: "Personnel",
  },
  {
    id: 2,
    title: "API Transport Management",
    description: "API REST/GraphQL pour gestion flottes, optimisation trajets (algorithme Dijkstra), suivi GPS temps réel + dashboard admin.",
    year: 2025,
    type: "Backend",
    technologies: ["Ruby on Rails", "PostgreSQL", "Redis", "Docker", "GraphQL"],
    link: "https://example.com",
    github: "https://github.com/username/transport-api",
    video: "https://www.youtube.com/embed/example1",
    mode: "Stage",
  },
  {
    id: 3,
    title: "App Mobile Santé Publique",
    description: "App cross-platform pour suivi vaccinal, rappels SMS, géolocalisation centres santé + sync offline-first avec Firebase.",
    year: 2025,
    type: "Mobile",
    technologies: ["React Native", "Expo", "Firebase", "PWA"],
    link: "https://example.com",
    github: "https://github.com/username/health-app",
    video: "https://www.youtube.com/embed/example2",
    mode: "Freelance",
  },
  {
    id: 4,
    title: "Détection Pneumonie IA",
    description: "CNN pour diagnostic automatique pneumonie (94% précision) sur 15k radiographies + déploiement Streamlit + API FastAPI.",
    year: 2024,
    type: "IA/ML",
    technologies: ["Python", "TensorFlow 2", "FastAPI", "Streamlit"],
    link: "https://example.com",
    github: "https://github.com/username/pneumonia-detection",
    video: "https://www.youtube.com/embed/example3",
    mode: "Académique",
  },
  {
    id: 5,
    title: "Hôpital Digital Dashboard",
    description: "ERP hospitalier complet : RDV, facturation, stocks, rapports PDF/Excel + rôles RBAC + audit trail.",
    year: 2025,
    type: "Web",
    technologies: ["Ruby on Rails", "PostgreSQL", "Hotwire", "Stimulus"],
    link: "https://example.com",
    github: "https://github.com/username/hospital-system",
    video: "https://www.youtube.com/embed/example4",
    mode: "Stage",
  },
  {
    id: 6,
    title: "Chatbot E-commerce IA",
    description: "Bot conversationnel GPT-4 personnalisé (RAG) pour 35% ↑ conversion + intégration Shopify/WooCommerce.",
    year: 2024,
    type: "IA/ML",
    technologies: ["Python", "OpenAI GPT-4", "FastAPI", "React"],
    link: "https://example.com",
    github: "https://github.com/username/ai-chatbot",
    video: "https://www.youtube.com/embed/example5",
    mode: "Freelance",
  },

  // 🔥 NOUVEAUX PROJETS 7-12
  {
    id: 7,
    title: "Système Réservation Multi-Transport",
    description: "Plateforme multimodale (bus, taxi, ferry) Madagascar avec paiement mobile (MVola), geofencing + optimisation IA.",
    year: 2025,
    type: "Web",
    technologies: ["Next.js", "Node.js", "MongoDB", "Mapbox"],
    link: "https://example.com",
    github: "https://github.com/username/transport-booking",
    video: "https://www.youtube.com/embed/example6",
    mode: "Académique",
  },
  {
    id: 8,
    title: "Analyseur Routier Automatisé",
    description: "Pipeline CV + ML pour évaluation automatique routes (IRM Madagascar) : détection nids-de-poule, classification PCI.",
    year: 2025,
    type: "IA/ML",
    technologies: ["Python", "YOLOv8", "OpenCV", "Pandas"],
    link: "https://example.com",
    github: "https://github.com/username/road-analyzer",
    video: "https://www.youtube.com/embed/example7",
    mode: "Recherche",
  },
  {
    id: 9,
    title: "PWA Clinique Mobile",
    description: "Progressive Web App pour cliniques rurales : gestion offline patients, sync auto, QR codes consultation.",
    year: 2026,
    type: "Web",
    technologies: ["React", "PouchDB", "Service Workers", "Tailwind"],
    link: "https://example.com",
    github: "https://github.com/username/mobile-clinic-pwa",
    video: "https://www.youtube.com/embed/example8",
    mode: "Personnel",
  },
  {
    id: 10,
    title: "Dashboard Transport Public",
    description: "Admin panel temps réel pour gestion flottes TNR (Toliara) : heatmap, prédictions retards, alertes maintenance.",
    year: 2025,
    type: "Web",
    technologies: ["React", "Node.js", "Socket.io", "Chart.js"],
    link: "https://example.com",
    github: "https://github.com/username/transport-dashboard",
    video: "https://www.youtube.com/embed/example9",
    mode: "Stage",
  },
  {
    id: 11,
    title: "Prédiction Trafic Urbain",
    description: "Modèle LSTM pour prédiction trafic Toliara (85% précision) basé données GPS historiques + intempéries.",
    year: 2025,
    type: "IA/ML",
    technologies: ["Python", "Keras", "Scikit-learn", "SHAP"],
    link: "https://example.com",
    github: "https://github.com/username/traffic-prediction",
    video: "https://www.youtube.com/embed/example10",
    mode: "Académique",
  },
  {
    id: 12,
  title: "Microservices HealthTech",
    description: "Architecture microservices pour télémédecine : auth, RDV vidéo, ordonnances numériques, facturation automatique.",
    year: 2026,
    type: "Backend",
    technologies: ["Node.js", "NestJS", "RabbitMQ", "Kubernetes"],
    link: "https://example.com",
    github: "https://github.com/username/healthtech-microservices",
    video: "https://www.youtube.com/embed/example11",
    mode: "Personnel",
  },
  {
    id: 13,
    title: "Analyse Sentiment Patients",
    description: "NLP pour analyse avis médicaux malgaches (français/malagasy) : détection satisfaction, alertes urgentes.",
    year: 2025,
    type: "IA/ML",
    technologies: ["Python", "HuggingFace", "spaCy", "MongoDB"],
    link: "https://example.com",
    github: "https://github.com/username/patient-sentiment",
    video: "https://www.youtube.com/embed/example12",
    mode: "Recherche",
  },
  {
    id: 14,
    title: "Optimiseur Itinéraires Ruraux",
    description: "Algorithme A* + contraintes malgaches (état routes, ferry horaires) pour livreurs/distributeurs médicaux.",
    year: 2026,
    type: "Web",
    technologies: ["React", "FastAPI", "Neo4j", "Leaflet"],
    link: "https://example.com",
    github: "https://github.com/username/rural-routing",
    video: "https://www.youtube.com/embed/example13",
    mode: "Freelance",
  },
  {
    id: 15,
    title: "IoT Monitoring Frigo Médical",
    description: "Système embarqué + dashboard pour suivi température vaccins (Toliara) avec alertes SMS + blockchain traçabilité.",
    year: 2026,
    type: "IoT",
    technologies: ["Node-RED", "MQTT", "InfluxDB", "React"],
    link: "https://example.com",
    github: "https://github.com/username/medical-fridge-iot",
    video: "https://www.youtube.com/embed/example14",
    mode: "Recherche",
  },
  {
    id: 16,
    title: "Marketplace Freelance Santé",
    description: "Plateforme matching médecins/patients avec géolocalisation, calendriers intelligents, Stripe + IA matching.",
    year: 2026,
    type: "Web",
    technologies: ["Next.js", "Prisma", "Supabase", "Stripe"],
    link: "https://example.com",
    github: "https://github.com/username/health-marketplace",
    video: "https://www.youtube.com/embed/example15",
    mode: "Personnel",
  },
  {
    id: 17,
    title: "Simulateur Épidémies",
    description: "Modèle SIR + agent-based pour simulation épidémies Madagascar avec interface interactive + export rapports.",
    year: 2025,
    type: "IA/ML",
    technologies: ["Python", "Plotly Dash", "NetworkX"],
    link: "https://example.com",
    github: "https://github.com/username/epidemic-simulator",
    video: "https://www.youtube.com/embed/example16",
    mode: "Académique",
  },
  {
    id: 18,
    title: "OCR Ordonnances Malgaches",
    description: "Vision IA pour extraction automatique données ordonnances manuelles (fr/malgache) + validation pharmacie.",
    year: 2026,
    type: "IA/ML",
    technologies: ["Tesseract", "PaddleOCR", "FastAPI", "React"],
    link: "https://example.com",
    github: "https://github.com/username/prescription-ocr",
    video: "https://www.youtube.com/embed/example17",
    mode: "Freelance",
  },
];

export type Project = {
  id: number;
  title: string;
  description: string;
  year: number;
  type: "Web" | "Backend" | "Mobile" | "IA/ML" | "IoT";
  technologies: string[];
  link: string;
  github: string;
  video: string;
  mode: "Personnel" | "Stage" | "Freelance" | "Académique" | "Recherche";
};


export default PROJECTS;
